export const
    Interface = {
        ALERT: 'Alert',
        BUTTON: 'Button',
        SENSOR_BINARY: 'SensorBinary',
        SENSOR_IMAGE: 'SensorImage',
        SENSOR_MULTILEVEL: 'SensorMultilevel',
        SWITCH_BINARY: 'SwitchBinary',
        SWITCH_MULTILEVEL: 'SwitchMultilevel'
    },
    Type = {
        Alert: 'Alert',
        BinarySensor: 'BinarySensor',
        Button: 'Button',
        Camera: 'Camera',
        Chime: 'Chime',
        Dimmer: 'Dimmer',
        DuskSensor: 'DuskSensor',
        Group: 'Group',
        Hvac: 'Hvac',
        LightSwitch: 'LightSwitch',
        Lock: 'Lock',
        MotionSensor: 'MotionSensor',
        OpenSensor: 'OpenSensor',
        PowerSwitch: 'PowerSwitch',
        Projector: 'Projector',
        Receptacle: 'Receptacle',
        Siren: 'Siren',
        Switch: 'Switch',
        Task: 'Task',
        Temperature: 'Temperature',
        ToggleButton: 'ToggleButton'
    },
    interfaceOfType = type => ({
        [Type.Alert]: Interface.ALERT,
        [Type.Button]: Interface.BUTTON,
        [Type.Camera]: Interface.SENSOR_IMAGE,
        [Type.Chime]: Interface.SWITCH_BINARY,
        [Type.Dimmer]: Interface.SWITCH_MULTILEVEL,
        [Type.DuskSensor]: Interface.SENSOR_BINARY,
        [Type.Group]: Interface.SWITCH_BINARY,
        [Type.LightSwitch]: Interface.SWITCH_BINARY,
        [Type.Lock]: Interface.SWITCH_BINARY,
        [Type.MotionSensor]: Interface.SENSOR_BINARY,
        [Type.OpenSensor]: Interface.SENSOR_BINARY,
        [Type.PowerSwitch]: Interface.SWITCH_BINARY,
        [Type.Projector]: Interface.SWITCH_BINARY,
        [Type.Receptacle]: Interface.SWITCH_BINARY,
        [Type.Siren]: Interface.SWITCH_BINARY,
        [Type.Switch]: Interface.SWITCH_BINARY,
        [Type.Task]: Interface.SWITCH_BINARY,
        [Type.Temperature]: Interface.SENSOR_MULTILEVEL,
        [Type.ToggleButton]: Interface.BUTTON
    }[type])
